# Global settings for naive-backup (Debian default)

# (Required) The GPG key ID or email address of the recipient.
# ENCRYPT_RECIPIENT="your-gpg-email@example.com"

# (Required) The directory to store backup files.
BACKUPDIR="/var/backups/naive"

# (Optional) A prefix for all backup files.
# PREFIX="my-server-backup"

# (Optional) The percentage difference at which to create a new full backup.
# SIZE_THRESHOLD=15

# (Required for content-based backups) Work directory with 0700 permissions.
# CONTENT_WORK_DIR="/var/cache/naivebackup"
